# This file contains instructions for the build server Travis
# The build is running on https://travis-ci.com/.
sudo: required
dist: trusty
language: node_js
node_js:
  - '10.16.0'
env:
  global:
    # $GH_TOKEN Token to access GitHub repo for deploying to GitHub Pages
    secure: MkDemB4Dtt3jr1XJmLdmQUdP3gKJ4uNitKyi00SeslVj4P3P2LRbTdRGu7U9WYT9hSW5VocvwVvYqz6WuTnSK1ODw772WTRAwxBbfSrMCkYb8IF7HbNqbIvDtlptnKl7vePMVs+F/ZWEd9ALlJ+fjpFqPmBc8LrGJY2fbBnprxQjQo3iQg0N7ThLc6xlMKdTlio+QFuVythC26Ni7w25Bz3ZeA5dd/0+mF3rPKRQzCrIapADBO2pG+WQ2PuQQpJb/WX9cnSkcKMsjBfvlA/Apsr875qvfprAS68/zRhGzssKn578blEhzi61w1Jz+0VM+dgTuYSp7y+0vNhmNZcI5h3fh6wEntWEWi57isKkf355mNIo65UWqATR2jFntX85qEQoyr1HgYUYr2QdqJIorIn2YrjS1VxmxeGGCvlqQIz/nUr+bePoqBdUM4hOhuGS0xcG74Sh7HMpj8UqIT0prfteO9RKY3jJdBAaUORe1y2L7RFVUO5P9CQzZAWv1s/UppXxKu3KfrbeooW0Uc80Y7b79t+FTiHOn8PwLPtxR9AkkHk9pvPyELRWOvr7O8qhIz966ZzR5rCL8/FYENlI11XLZD/IR2mCIRsX14aGLkwhLX7hSXeS1sjW5CfF4nJ14dGRr9zd5r+/+z3ItnwyFPS1aasXv01YbSWK4fd2VzY=
install:
- npm install
script:
- ng lint
- npm run build-ghpages
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: dist/change-detection
  on:
    branch: master
